name: Project CICD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint-and-pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pylint, Flake8 and Pydocstyle
        run: ./lint.sh

      - name: PyTest
        run: |
          touch ./tests/__init__.py
          python -m pytest ./tests
